baseURL = "http://hongsenliu.github.io/"
languageCode = "en-us"
title = "ITO"

copyright = "Copyright &copy; 2017 - Hongsen Liu"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "hongsenliu" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Hongsen Liu"
    #github = ""
    #gitlab = ""
    #linkedin = ""
    #facebook = ""
    #twitter = ""
    #instagram = ""

[params]
    tagline = "Input|Think|Output"

